// Copies the ABIs of the Forge artifacts into src/abi.ts so the dapp always matches the contracts.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, "../../out");
const names = ["IndexVault", "IndexVaultFactory", "IndexConfig", "ChainlinkAdapter"];
let ts = "// Generated by scripts/abi.mjs from ../out — do not edit.\n";
for (const n of names) {
  const p = resolve(out, `${n}.sol/${n}.json`);
  if (!existsSync(p)) {
    console.error(`missing ${p} — run 'forge build' in the repo root first`);
    process.exit(1);
  }
  const abi = JSON.parse(readFileSync(p, "utf8")).abi;
  ts += `export const ${n}Abi = ${JSON.stringify(abi)} as const;\n`;
}
ts += `export const erc20Abi = ${JSON.stringify([
  { type: "function", name: "name", inputs: [], outputs: [{ type: "string" }], stateMutability: "view" },
  { type: "function", name: "symbol", inputs: [], outputs: [{ type: "string" }], stateMutability: "view" },
  { type: "function", name: "decimals", inputs: [], outputs: [{ type: "uint8" }], stateMutability: "view" },
  { type: "function", name: "balanceOf", inputs: [{ name: "a", type: "address" }], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "allowance", inputs: [{ name: "o", type: "address" }, { name: "s", type: "address" }], outputs: [{ type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "approve", inputs: [{ name: "s", type: "address" }, { name: "v", type: "uint256" }], outputs: [{ type: "bool" }], stateMutability: "nonpayable" },
])} as const;\n`;
writeFileSync(resolve(here, "../src/abi.ts"), ts);
console.log("wrote src/abi.ts");
